/**
 * 由 scripts/make-icons.mjs 生成，请勿手工编辑。
 *
 * 托盘图标内联为 data URL：主进程在开发态与打包态都能直接拿到，
 * 不需要把资源文件额外搬进 out/ 或 app.asar 的资源目录。
 */
export const TRAY_ICON_DATA_URL =
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABIUlEQVR42mMQFJVmQMICQLpBUFT6vKCo9H8q4/NQswWQ7US2PEFQVPo9DSxGx++hdqE4IIEOFqPjBJgDBOjkc2whIcAAjZf/A4QbGGiU4IhOmAz4FCioaP7v6Or9f+Tosf/Llq8C86ntCLwO2Lptx39k8OHDx/92jm70cwA2QG1HkOwAGMjKLaS9A6bPnI3XEZXV9bR1AAiDEh8+AJKnqQNAGJQT8AFQYiU3hzAQqxAU5/jApctXyHIEAymKfQNCwLkAnyNo6gAQBmVBfI4AOXL4OmBAo2BAE+GAZsMBLYhILYqj45LAoYWO8dUbVKuMQLmDnMqLatUxKIeQU3FRtUEC8iW2KMBXaw6KJtmAN0oHvFk+4B2TAe+aDYrO6YB1zwHNAIfaQWJJ3AAAAABJRU5ErkJggg=='
